name = "siren"
compatibility_date = "2025-06-04"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "3b4661d3444940da92d6d88e963d13da"

[vars]
UUID = "aae9e94e-1bcd-44ef-90ce-20b427ed7eed"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
